### ISSUE TITLE
心好痛、、、为什么不早点写这个、、

### ISSUE THREAD

**Issue by yangtiao** [phodal/serverless-guide#1]
第一次接触serverless，同样也是第一次写node代码。自己搭建的架构是以lambda的handler为路由，通过传的参数来判断请求具体哪个function，最后返回结果集。现在看了你这个感觉我好傻，但是项目已经开发了快两个星期了，怎么办、、、、

**Comment by phodal** [comment]
@yangtiao 重写，哈哈哈

**Comment by yangtiao** [comment]
lambda里的nodejs以express为基础，前端代码放在S3，页面的所有操作通过ajax请求api接口
这个结构是没问题的吧？

**Comment by phodal** [comment]
这个结构没有问题。


今天在玩这个《[Serverless API Gateway Route 53 自定义域名](https://github.com/phodal/serverless-guide/tree/master/wechat) 》。
